@client.command(name="mute")
@commands.has_permissions(manage_messages=True)
async def mute(ctx, member: discord.Member,time,*,reason="Nincs indok megadva"):
    a=client.get_channel(980394018917740584)
    reason = "".join(reason)
    muted_role=discord.utils.get(ctx.guild.roles, id=980410642244730931)
    time_convert = {"s":1, "m":60, "h":3600,"d":86400}
    tempmute= int(time[0]) * time_convert[time[-1]]
    await member.add_roles(muted_role)
    embed = discord.Embed(description= f"✅ Anonymous Némítva", color=discord.Color.green(),timestamp=ctx.message.created_at)
    embed2=discord.Embed(color=0x9999ff,timestamp=ctx.message.created_at)
    embed2.set_author(name=f"{member} Némítva", icon_url=member.avatar_url)
    embed2.add_field(name=f"{member} Némítva!",value=f"\nIdő: {time}\nIndok: {reason}\nModerátor: {ctx.author.mention}")
    embed2.set_thumbnail(url=member.avatar_url)
    embed2.set_footer(text=member.id)
    await ctx.send(embed=embed)
    await a.send(embed=embed2)
    embed4=discord.Embed(color=0x9999ff,timestamp=ctx.message.created_at)
    embed4.set_author(name=f"{member}", icon_url=member.avatar_url)
    embed4.set_thumbnail(url=member.avatar_url)
    embed4.add_field(name=f"{member} Némítva lettél itt: {ctx.guild.name}",value=f"\nIdő: {time}\nIndok: {reason}")
    embed4.set_footer(text=member.id)
    await member.send(embed=embed4)
    await asyncio.sleep(tempmute)
    await member.remove_roles(muted_role)
    embed3=discord.Embed(color=0x00ff99,timestamp=ctx.message.created_at)
    embed3.set_author(name=f"{member}", icon_url=member.avatar_url)
    embed3.set_thumbnail(url=member.avatar_url)
    embed3.add_field(name=f"{member} némítása lejárt!",value=f"\nIndok: {reason}\nModerátor: {ctx.author.mention}")
    embed3.set_footer(text=member.id)
    await a.send(embed=embed3)
    embed5=discord.Embed(color=0x9999ff,timestamp=ctx.message.created_at)
    embed5.set_author(name=f"{member}", icon_url=member.avatar_url)
    embed5.set_thumbnail(url=member.avatar_url)
    embed5.add_field(name=f"{member} Nemításod lejárt itt: {ctx.guild.name}",value="\u200b")
    embed5.set_footer(text=member.id)
    await member.send(embed=embed5)
